spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 111111
      initial-size: 1
      min-idle: 1
      max-active: 20

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.qfedu.fmmall.entity